### ISSUE TITLE
Data inconsistent, protocol ??

### ISSUE THREAD

**Issue by Festix** [klightspeed/BrassMonkeyFridgeMonitor#1]
Hell Sir, First of all, thanks for your share, it looks pretty good. 
I found and tested your script looking for some python BLE interface for my new Alpicool T50 dual zone mobile fridge.

Working on the script I found that function get_packet_data() is facing some issue on the protocol after sending: **query command b'\xfe\xfe\x03\x01\x02\x00'.**

**the character "!" which is 33 is the pktlen from the BLE answer....   But, the data string is shorter than this..
print(data) = bytearray(b'\xfe\xfe!\x01\x00\x01\x00\x01\xf3\x14\xec\x02\x00\x00\x00\x00\xfd\x00\xf5d')**

What do you think ??
Are there some extra experience to help improve the protocol options ??
Can I help with some extra test ??

Best regards.
Esteban

**Comment by klightspeed** [comment]
One thing I had missed, which didn't seem to be necessary on my test setup, was to increase the MTU.  Apparently the default MTU for BLE is 20 bytes, which this response agrees with.

**Comment by klightspeed** [comment]
Looking at <https://github.com/hbldh/bleak/issues/168>, it looks like setting the MTU is only supported on Android.

Looking at <https://github.com/hbldh/bleak/issues/1227>, some older adaptors don't support the LE Data Packet Length Extension, and so devices will fragment the BLE packets.

Would it please be possible to perform a Wireshark capture on the bluetooth interface and see what MTU is being negotiated by the OS, and whether the fridge is fragmenting the packet if the controller does not support the LE Data Packet Length Extension (or alternatively truncating the packet if the controller does support the LE Data Packet Length Extension)?

**Comment by klightspeed** [comment]
I just performed a packet capture on my device (a Raspberry Pi Zero W) communicating with my fridge (a single-zone fridge), and:
* The Bluetooth stack negotiated a MTU of 508 bytes
* The LE Data Packet Length Extension is _not_ supported,
* The fridge _is_ fragmenting the 24 byte notification, and
* The Bluetooth stack reassembled the notification before passing it to the client.

![image](https://github.com/klightspeed/BrassMonkeyFridgeMonitor/assets/147116/2f077257-587c-4d4f-9cf3-bdeb3c3b1571)
